CREATE TABLE accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  name VARCHAR(255) NOT NULL COMMENT 'users given name',
  email VARCHAR(255) NOT NULL COMMENT 'auth email',
  picture VARCHAR(255) NOT NULL COMMENT 'picture url'
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE projects(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  name VARCHAR(255) NOT NULL COMMENT 'project name',
  creatorId VARCHAR(255) NOT NULL COMMENT 'FK: user account',
  FOREIGN KEY(creatorId) REFERENCES accounts(id) ON DELETE CASCADE
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE boards(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  name VARCHAR(255) NOT NULL COMMENT 'board name',
  creatorId VARCHAR(255) NOT NULL COMMENT 'FK: user account',
  projectId INT NOT NULL COMMENT 'FK: project id',
  FOREIGN KEY(creatorId) REFERENCES accounts(id) ON DELETE CASCADE,
  FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE CASCADE
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE tasks(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  description VARCHAR(255) NOT NULL COMMENT 'task description',
  creatorId VARCHAR(255) NOT NULL COMMENT 'FK: user account',
  boardId INT NOT NULL COMMENT 'FK: board id',
  FOREIGN KEY(creatorId) REFERENCES accounts(id) ON DELETE CASCADE,
  FOREIGN KEY(boardId) REFERENCES boards(id) ON DELETE CASCADE
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE collaborators(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'primary key',
  accountId VARCHAR(255) NOT NULL COMMENT 'account id',
  projectId INT NOT NULL COMMENT 'project id'
) DEFAULT CHARSET utf8 COMMENT '';